#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidSQLite.Resource", IsApplication=true)]

namespace AndroidSQLite
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int Slide_Right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Slide_Up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int CloseButton = 2131165189;
			
			// aapt resource value: 0x7f07000b
			public const int btnAdd = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int btnDelete = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int btnSaveFr = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int edtAge = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int edtAgeFr = 2131165186;
			
			// aapt resource value: 0x7f07000a
			public const int edtEmail = 2131165194;
			
			// aapt resource value: 0x7f070003
			public const int edtEmailFr = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int edtName = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int edtNameFr = 2131165185;
			
			// aapt resource value: 0x7f07000d
			public const int listView = 2131165197;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int textView2 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int textView3 = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int fragment_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int list_view_dataTemplate = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int dialog_animation = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
